# See full list at:
# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

max_width = 80
format_strings = true
merge_imports = true
normalize_comments = true
wrap_comments = true

reorder_impl_items = true
use_try_shorthand = true

error_on_line_overflow = true
error_on_unformatted = true

unstable_features = true
