version: "2"

services:
  medea:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    image: ${COMPOSE_IMAGE_NAME}:${COMPOSE_IMAGE_VER}
    environment:
      RUST_LOG: ${RUST_LOG}
      MEDEA_CONF: ${MEDEA_CONF}
      MEDEA_CONTROL__STATIC_SPECS_DIR: ${MEDEA_CONTROL__STATIC_SPECS_DIR}
    volumes:
      - ./${MEDEA_CONF}:/${MEDEA_CONF}:ro
      - ./${MEDEA_CONTROL__STATIC_SPECS_DIR}:/${MEDEA_CONTROL__STATIC_SPECS_DIR}:ro
    network_mode: host
