apiVersion: v1
entries:
  medea-demo:
  - apiVersion: v2
    appVersion: 0.2.0-dev
    created: "2020-08-27T15:39:57.682154501Z"
    digest: b911ef9f1dc8a1cac451ea5e73c1eddcfce884112dc96a509bb25447653034d1
    name: medea-demo
    type: application
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.2.0-dev
    created: "2020-08-27T15:39:57.68127109Z"
    digest: d82667014946f79fd3ff34e6dca7fdb230f642a49027b9ef08b7a8e61b0d5492
    name: medea-demo
    type: application
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.2.0-dev
    created: "2020-08-27T15:39:57.679667971Z"
    digest: 263433880d833800dcfd4238f447e1ff38a0f843e1f57726f559411def49d210
    name: medea-demo
    type: application
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.2.0-dev
    created: "2020-08-27T15:39:57.67877646Z"
    digest: 2b96d0ddf9aca55c797a528750407a71367e57d738fc74ef2682bf3c59771761
    name: medea-demo
    type: application
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.677701047Z"
    digest: d049dbcc5fe68e0493ea0dc38fd4753631d2fc03964f5f83f4a727ef75c7a760
    name: medea-demo
    type: application
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.676712535Z"
    digest: dc121dd16e286f51ef505b5644a8c20a091f95e1e522daabe57fcdea658c3064
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.675804325Z"
    digest: 352da84002120076aa671506165f9f03cb925e7174ed47793bdbfd7a4c067838
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.674854213Z"
    digest: e4bdbcd139aa1e66f2a27bd22f70143c8b0af625e0aefc1cd3b4530f41f2e0a0
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.668196734Z"
    digest: ac4e5cee69a8c49cd42b3b96875de82595bf25a5f32a849cafbc006518e5fa2f
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-08-27T15:39:57.666744416Z"
    digest: 309cdd8aa637c7385122b1d323dd73a3a26e10d0f8bfaefc4ea9e0b3b127610b
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-27T15:39:57.665335799Z"
